### ISSUE TITLE
Add features and usage to README

### ISSUE THREAD

**Issue by bijanbwb** [encours/codeschool-app#1]
So awesome that you put this together!

I couldn't tell what the features are or how to use it. Maybe add to the README what the features are for the extension and some steps on how to use the extension after installation?

**Comment by GloverDonovan** [comment]
I'm looking into this.

The installation on Chrome OS is almost instant, but Windows machines may require an additional step. I'll update the readme once I have access to test in a Windows environment.

**Comment by GloverDonovan** [comment]
Hello,

I followed the usage instructions with a Windows computer and they seemed to be identical to how it's done on Chrome OS.
![capturea](https://cloud.githubusercontent.com/assets/2374245/6450772/358307c8-c0f8-11e4-9912-c6cffd8139d8.png)
For now I won't change anything, although you can submit a pull request with the content that you think needs to be improved.
